week2 - Ruby on Rails/BookStore/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'books#index'
  post '/books/search' => 'books#search', as: 'book_search'
  resources :books do
  	resources :ratings
  end

end

week2 - Ruby on Rails/BookStore/app/models/book.rb
class Book < ActiveRecord::Base
	has_many :ratings
	validates :name, presence: true, uniqueness: true

	def average_total_rating
		scores = []
		if self.ratings.any?
			self.ratings.each do |rating|
				scores << rating.score
			end	
			sum_ratings = scores.reduce(:+)
			length = scores.length
			average_rating = (sum_ratings.to_f / length.to_f).round(1)
		else 
			return 0
		end
	end

	def self.newest_books
		order("created_at DESC")
	end

	def self.search(query)
		where("name like ? OR description like ?", "%#{query}%", "%#{query}%")
	end

	def self.order_by_rating word_search
		search(word_search).sort_by{|book| book.average_total_rating }.reverse
	end
end

week2 - Ruby on Rails/BookStore/app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :book
	validates :user, presence: true, uniqueness: true
	validates :score, presence: true, numericality: true, inclusion: {in: 1..5} 
end

week2 - Ruby on Rails/BookStore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week2 - Ruby on Rails/BookStore/app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.newest_books
	end

	def search
		@books = Book.order_by_rating(params[:search])
		render 'index'
	end

	def show
		@book = Book.find params[:id]
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new params_book
		if @book.save
			flash[:notice] = "Book created succesfully."
			redirect_to @book
		else
			flash.now[:errors] = @book.errors.full_messages
			render 'new'
		end
	end

	def edit
		@book = Book.find params[:id]
	end

	def update
		@book = Book.find params[:id]
		if @book.update params_book
			flash[:notice] = "Book updated succesfully."
			redirect_to @book
		else
			flash.now[:errors] = @book.errors.full_messages
			render 'edit'
		end
	end

	def destroy
		book = Book.find params[:id]
		book.destroy
		redirect_to books_path		
	end

	private
	def params_book
		params.require(:book).permit(:name, :description, :price)
	end
end

week2 - Ruby on Rails/BookStore/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
	def index
		begin
			@book = Book.find params[:book_id]
			@ratings = @book.ratings
		rescue ActiveRecord::RecordNotFound
			render 'no_ratings_found'
		end
	end

	def show
		@book = Book.find params[:id]
		@ratings = @book.ratings
	end

	def new
		@book = Book.find params[:book_id]
		@rating = @book.ratings.new
	end

	def create
		@book = Book.find params[:book_id]
		@rating = @book.ratings.new params_rating
		if @book.save
			flash[:notice] = "Rating saved succesfully."
			redirect_to @book
		else
			flash.now[:errors] = @rating.errors.full_messages
			render 'new'
		end
	end

	private
	def params_rating
		params.require(:rating).permit(:book_id, :score, :user)
	end
end

week2 - Ruby on Rails/BookStore/app/helpers/application_helper.rb
module ApplicationHelper
end

week2 - Ruby on Rails/BookStore/app/helpers/books_helper.rb
module BooksHelper
end

week2 - Ruby on Rails/BookStore/app/helpers/ratings_helper.rb
module RatingsHelper
end

week2 - Ruby on Rails/BookStore/app/views/ratings/index.html.erb
<h1> <%= "Rating of #{@book.name}" %></h1>

<br>

<h3> <%= "Average rating" %> : <%= @book.average_total_rating %></h3>

	<dl>
	<% @ratings.each do |rating| %>
		<dd>
			<%= rating.user %> : <%= rating.score %>
		</dd>
	<% end %>
</dl>

<br>

<p>
    <%= link_to 'New Rating', new_book_rating_path(@book) %> | 
    <%= link_to 'Back', book_path(@book) %>
</p>

week2 - Ruby on Rails/BookStore/app/views/ratings/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error_msg| %>
    <li><%= error_msg %></li>
  <% end %>
<% end %>

<%= form_for [@book, @ratings] do |f| %>
      
      
    <div>    
      <h2>New rating</h2>
   
          <p>
              <%= f.label :user %><br>
              <%= f.text_field :user %>
          </p>

          <p>
              <%= f.label :score %> (from 1 to 5)<br>
              <%= f.text_field :score %>
          </p>


      <div><%= f.submit 'Save' %></div>

   </div>
 <% end %>

  <p>
      <%= link_to 'Back to Books', books_path%>
  </p>

week2 - Ruby on Rails/BookStore/app/views/ratings/no_ratings_found.html.erb
<h2>No ratings found !!</h2>