week4 - JavaScript/AuctionsSite/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'auctions#index'
  resources :users do
    resources :auctions do
    	resources :user do
    		resources :bids
    	end
    end
  end
end

week4 - JavaScript/AuctionsSite/app/models/auction.rb
class Auction < ActiveRecord::Base
	belongs_to :user
	has_many :user

	validates :item, :price, presence: true
end

week4 - JavaScript/AuctionsSite/app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :auction
	belongs_to :user

	validates :bidding, presence: true
end

week4 - JavaScript/AuctionsSite/app/models/user.rb
class User < ActiveRecord::Base
	has_many :auctions
	has_many :bids

	validates :name, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true, format: {with: /[a-z0-9._-]+@[a-z0-9.-]+\.[a-z]{2,4}/ }
end

week4 - JavaScript/AuctionsSite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week4 - JavaScript/AuctionsSite/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
	def index
		begin
			@user = User.find params[:user_id]
			@auctions = @user.auctions
		rescue ActiveRecord::RecordNotFound
			render 'no_auctions_found'
		end
	end

	def show
		@user = User.find params[:id]
		@auctions = @user.auctions
	end

	def new
		@user = User.find params[:user_id]
		@auctions = @user.auctions.new
	end

	def create
		@user = User.find params[:user_id]
		@auction = @user.auctions.new params_auction
		if @user.save
			flash[:notice] = "Auction saved succesfully."
			redirect_to @user
		else
			flash.now[:errors] = @auction.errors.full_messages
			render 'new'
		end
	end

	private
	def params_auction
		params.require(:auction).permit(:user_id, :item, :description, :end_date, :price)
	end
end

week4 - JavaScript/AuctionsSite/app/controllers/bids_controller.rb
class BidsController < ApplicationController
	def index
		begin
			@auction = Auction.find params[:id]
			@bids = @auction.bids
		rescue ActiveRecord::RecordNotFound
			render 'no_bids_found'
		end
	end

	def show
		@auction = Auction.find params[:id]
		@bids = @auction.bids
	end

	def new
		@auction = Auction.find params[:id]
		@bid = @auction.bids.new
	end

	def create
		@auction = Auction.find params[:id]
		@bid = @auction.bids.new params_bid
		if @user.save
			flash[:notice] = "Bid saved succesfully."
			redirect_to @auction
		else
			flash.now[:errors] = @bid.errors.full_messages
			render 'new'
		end
	end

	private
	def params_bid
		params.require(:bid).permit(:user_id, :auction_id, :bid)
	end
end

week4 - JavaScript/AuctionsSite/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find params[:id]
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new params_user
		if @user.save
			flash[:notice] = "User created succesfully."
			redirect_to @user
		else
			flash.now[:errors] = @user.errors.full_messages
			render 'new'
		end
	end

	def edit
		@user = User.find params[:id]
	end

	def update
		@user = User.find params[:id]
		if @user.update params_user
			flash[:notice] = "User updated succesfully."
			redirect_to @user
		else
			flash.now[:errors] = @user.errors.full_messages
			render 'edit'
		end
	end

	def destroy
		user = User.find params[:id]
		user.destroy
		redirect_to users_path		
	end

	private
	def params_book
		params.require(:user).permit(:name, :email)
	end
end

week4 - JavaScript/AuctionsSite/app/helpers/application_helper.rb
module ApplicationHelper
end

week4 - JavaScript/AuctionsSite/app/helpers/auctions_helper.rb
module AuctionsHelper
end

week4 - JavaScript/AuctionsSite/app/helpers/bids_helper.rb
module BidsHelper
end

week4 - JavaScript/AuctionsSite/app/helpers/users_helper.rb
module UsersHelper
end

week4 - JavaScript/AuctionsSite/app/views/auctions/edit.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error_msg| %>
    <li><%= error_msg %></li>
  <% end %>
<% end %>

<%= form_for @book do |f| %>
      
      
    <div>    
      <h2>Information</h2>

          <p>
              <%= f.label :item %><br>
              <%= f.text_field :item %>
          </p>    
          <p>
              <%= f.label :description %><br>
              <%= f.text_area :description %>
          </p>
          <p>
              <%= f.label :price %><br>
              <%= f.text_area :price %>
          </p>

          <p>
              <%= f.label :end_date %><br>
              <%= f.date_select :end_date %>
          </p>

      <div><%= f.submit 'Save' %></div>

   </div>
 <% end %>

  <p>
      <%= link_to 'Back to Books', books_path%>
  </p>

week4 - JavaScript/AuctionsSite/app/views/auctions/index.html.erb
<h1> Virgo's Auction Site </h1>

<dl>
	<% @auctions.each do |auction| %>
		<dd>
			<%= auction.item %> <%= link_to 'Read more', user_auction_path(@user,auction) %>
			<%= link_to 'Add a Bid', new_user_auction_bid_path(User.new(), auction) %>
		</dd>
	<% end %>
</dl>

<br>

<p>
    <%= link_to 'New auction', new_auction_path(@user) %>
</p>

week4 - JavaScript/AuctionsSite/app/views/auctions/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error_msg| %>
    <li><%= error_msg %></li>
  <% end %>
<% end %>

<%= form_for @auction do |f| %>
      
      
    <div>    
      <h2>Information</h2>

          <p>
              <%= f.label :item %><br>
              <%= f.text_field :item %>
          </p>    
          <p>
              <%= f.label :description %><br>
              <%= f.text_area :description %>
          </p>
          <p>
              <%= f.label :price %><br>
              <%= f.text_area :price %>
          </p>

          <p>
              <%= f.label :end_date %><br>
              <%= f.date_select :end_date %>
          </p>

      <div><%= f.submit 'Save' %></div>

   </div>
 <% end %>

  <p>
      <%= link_to 'Back to Auctions', user_auctions_path %>
  </p>

week4 - JavaScript/AuctionsSite/app/views/auctions/no_auctions_found.html.erb
<h2>No auctions found !!</h2> 

week4 - JavaScript/AuctionsSite/app/views/auctions/show.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h2>
	<strong>Product:</strong>
	<%= @auction.item %> (<%= link_to 'Edit auction', edit_user_auction_path(@auction) %>)</h2> 

<table>
	<tr>
		<td class="styleblack"> <strong>Product:</strong></td>
		<td><%= @auction.product %></td>
	</tr> 

	<tr>
		<td class="styleblack"> <strong>Description:</strong></td>
		<td><%= @auction.description %></td>
	</tr> 
	<tr> 
		<td class="styleblack"><strong>Price:</strong></td>
		<td><%= @auction.price %> </td>
	</tr> 

	<tr> 
		<td class="styleblack"><strong>End date:</strong></td>
		<td><%= @auction.end_date %> </td> 
	</tr> 

</table>

<br>
<%= link_to 'Back to auctions', auctions_path %> |
<%= link_to 'Add a new bid', new_user_auction_bid_path(@auction) %> 

week4 - JavaScript/AuctionsSite/app/views/bids/no_bids_found.html.erb
<h2>No bids found!!</h2>

week4 - JavaScript/AuctionsSite/app/views/users/edit.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error_msg| %>
    <li><%= error_msg %></li>
  <% end %>
<% end %>

<%= form_for @book do |f| %>
      
      
    <div>    
      <h2>Information</h2>

          <p>
              <%= f.label :name %><br>
              <%= f.text_field :name %>
          </p>    
          <p>
              <%= f.label :description %><br>
              <%= f.text_area :description %>
          </p>
          <p>
              <%= f.label :price %><br>
              <%= f.text_area :price %>
          </p>


      <div><%= f.submit 'Save' %></div>

   </div>
 <% end %>

  <p>
      <%= link_to 'Back to Books', books_path%>
  </p>

week4 - JavaScript/AuctionsSite/app/views/users/index.html.erb
<h1> Virgo's user Site </h1>

<dl>
	<% @users.each do |user| %>
		<dd>
			<%= user.name %> : <%= user.email %> 
			<%= link_to 'Edit', edit_user_path(user) %> |
			<%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"} %>
			<%= link_to 'Add an Auction', new_user_auction_path(user) %>
			<br> 
			<ul> 
				<% user.auctions.each do |auction| %>
				<li> <%= auction.item %> <%= link_to 'Show', user_auction_path(user, auction) %></li> 
				<% end %>
			</ul>
		</dd>
	<% end %>
</dl>
	
<br>

<p>
    <%= link_to 'New user', new_user_path %>

</p>

week4 - JavaScript/AuctionsSite/app/views/users/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error_msg| %>
    <li><%= error_msg %></li>
  <% end %>
<% end %>

<%= form_for @book do |f| %>
      
      
    <div>    
      <h2>Information</h2>

          <p>
              <%= f.label :name %><br>
              <%= f.text_field :name %>
          </p>    
          <p>
              <%= f.label :description %><br>
              <%= f.text_area :description %>
          </p>
          <p>
              <%= f.label :price %><br>
              <%= f.text_area :price %>
          </p>

      <div><%= f.submit 'Save' %></div>

   </div>
 <% end %>

  <p>
      <%= link_to 'Back to Books', books_path%>
  </p>

week4 - JavaScript/AuctionsSite/app/views/users/show.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h2>
	<strong>Name:</strong>
	<%= @book.name %> (<%= link_to 'Edit Book', edit_book_path(@book) %>)</h2> 

<table>
	<tr>
		<td class="styleblack"> <strong>Description:</strong></td>
		<td><%= @book.description %></td>
	</tr> 
	<tr> 
		<td class="styleblack"><strong>Price:</strong></td>
		<td><%= @book.price %> </td>

	</tr> 

	<tr> 
		<td class="styleblack"><strong>Average Rating:</strong></td>
		<td><%= @book.average_total_rating %> <%= link_to 'Show Ratings', book_ratings_path(@book) %> </td> 

	</tr> 

</table>

<br>
<%= link_to 'Back to Books', books_path %> |
<%= link_to 'Add a new rating', new_book_rating_path(@book) %> 